version: 2.1

orbs:
  build-tools: circleci/build-tools@2.5.0
  docker: circleci/docker@dev:alpha
  jq: circleci/jq@1.9.0
  orb-tools: circleci/orb-tools@8.27.1

jobs:
  test:
    parameters:
      executor:
        type: executor

      docker-version:
        type: string
        default: latest

      docker-compose-version:
        type: string
        default: latest

      dockerize-version:
        type: string
        default: latest

      install-goss:
        type: boolean
        default: true

      goss-version:
        type: string
        default: latest

      test-all-in-one-command:
        type: boolean
        default: false

      debug:
        type: boolean
        default: false

    executor: <<parameters.executor>>

    steps:
      - build-tools/install-ci-tools
      - jq/install

      - unless:
          condition: <<parameters.test-all-in-one-command>>
          steps:
            - docker/install-docker:
                version: <<parameters.docker-version>>

            - docker/install-docker-compose:
                version: <<parameters.docker-compose-version>>

            - docker/install-dockerize:
                version: <<parameters.dockerize-version>>

            - when:
                condition: <<parameters.install-goss>>
                steps:
                  - docker/install-goss:
                      version: <<parameters.goss-version>>
                      debug: <<parameters.debug>>


      - when:
          condition: <<parameters.test-all-in-one-command>>
          steps:
            - docker/install-docker-tools:
                docker-version: <<parameters.docker-version>>
                docker-compose-version: <<parameters.docker-compose-version>>
                dockerize-version: <<parameters.dockerize-version>>
                install-goss-dgoss: <<parameters.install-goss>>
                goss-version: <<parameters.goss-version>>
                debug: <<parameters.debug>>

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    test-publish-machine-master,
    test-publish-docker-master,
    test-latest-alpine-master,
    test-older-alpine-master,
    test-latest-machine-master,
    test-older-machine-master,
    test-latest-mac-master,
    test-older-mac-master,
    test-latest-docker-master,
    test-older-docker-master,
    test-latest-ci-docker-master,
    test-older-ci-docker-master,
    test-latest-alpine-altogether-master,
    test-older-alpine-altogether-master,
    test-latest-machine-altogether-master,
    test-older-machine-altogether-master,
    test-latest-mac-altogether-master,
    test-older-mac-altogether-master,
    test-latest-docker-altogether-master,
    test-older-docker-altogether-master,
    test-latest-ci-docker-altogether-master,
    test-older-ci-docker-altogether-master,
    test-latest-oracle-master,
    test-older-oracle-master,
    test-latest-oracle-altogether-master,
    test-older-oracle-altogether-master
  ]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          orb-name: circleci/docker
          context: orb-publishing
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: d9:97:a8:58:12:13:40:59:48:96:f8:10:be:b8:ba:07
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          cleanup-tags: true
          ssh-fingerprints: d9:97:a8:58:12:13:40:59:48:96:f8:10:be:b8:ba:07
          tag: master
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # build/publish
      - docker/publish:
          name: test-publish-machine-dev
          context: orb-publishing
          dockerfile: test.Dockerfile
          image: circlecipublic/docker-orb-test
          tag: $CIRCLE_BUILD_NUM-$CIRCLE_SHA1
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASS
          filters: *integration-dev_filters

      - docker/publish:
          name: test-publish-docker-dev
          executor: docker/docker
          context: orb-publishing
          use-remote-docker: true
          dockerfile: test.Dockerfile
          image: circlecipublic/docker-orb-test
          tag: $CIRCLE_BUILD_NUM-$CIRCLE_SHA1
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASS
          filters: *integration-dev_filters

      # alpine
      - test:
          name: test-latest-alpine-dev
          executor: orb-tools/alpine
          filters: *integration-dev_filters
          pre-steps: [run: apk add gnupg]

      - test:
          name: test-older-alpine-dev
          executor: orb-tools/alpine
          docker-version: v18.09.4
          docker-compose-version: 1.17.1
          dockerize-version: v0.4.0
          goss-version: v0.3.2
          filters: *integration-dev_filters
          pre-steps: [run: apk add gnupg]

      - test:
          name: test-latest-alpine-altogether-dev
          executor: orb-tools/alpine
          test-all-in-one-command: true
          filters: *integration-dev_filters
          pre-steps: [run: apk add gnupg]

      - test:
          name: test-older-alpine-altogether-dev
          executor: orb-tools/alpine
          test-all-in-one-command: true
          docker-version: v18.09.4
          docker-compose-version: 1.17.1
          dockerize-version: v0.4.0
          goss-version: v0.3.3
          filters: *integration-dev_filters
          pre-steps: [run: apk add gnupg]

      # machine
      - test:
          name: test-latest-machine-dev
          executor: orb-tools/machine
          filters: *integration-dev_filters

      - test:
          name: test-older-machine-dev
          executor: orb-tools/machine
          docker-version: v17.09.0-ce
          docker-compose-version: 1.20.0
          dockerize-version: v0.2.0
          goss-version: v0.3.4
          filters: *integration-dev_filters

      - test:
          name: test-latest-machine-altogether-dev
          executor: orb-tools/machine
          test-all-in-one-command: true
          filters: *integration-dev_filters

      - test:
          name: test-older-machine-altogether-dev
          executor: orb-tools/machine
          test-all-in-one-command: true
          docker-version: v17.09.0-ce
          docker-compose-version: 1.20.0
          dockerize-version: v0.2.0
          goss-version: v0.3.5
          filters: *integration-dev_filters

      # mac
      - test:
          name: test-latest-mac-dev
          executor: orb-tools/macos
          install-goss: false
          filters: *integration-dev_filters

      - test:
          name: test-older-mac-dev
          executor: orb-tools/macos
          docker-version: v17.12.1-ce
          docker-compose-version: 1.21.2
          dockerize-version: v0.5.0
          install-goss: false
          filters: *integration-dev_filters

      - test:
          name: test-latest-mac-altogether-dev
          executor: orb-tools/macos
          test-all-in-one-command: true
          install-goss: false
          filters: *integration-dev_filters

      - test:
          name: test-older-mac-altogether-dev
          executor: orb-tools/macos
          test-all-in-one-command: true
          docker-version: v17.12.1-ce
          docker-compose-version: 1.21.2
          dockerize-version: v0.5.0
          install-goss: false
          filters: *integration-dev_filters

      # docker
      - test:
          name: test-latest-docker-dev
          executor: orb-tools/node
          filters: *integration-dev_filters

      - test:
          name: test-older-docker-dev
          executor: orb-tools/node
          docker-version: v18.09.3
          docker-compose-version: 1.22.0
          dockerize-version: v0.6.0
          goss-version: v0.3.6
          filters: *integration-dev_filters

      - test:
          name: test-latest-docker-altogether-dev
          executor: orb-tools/node
          test-all-in-one-command: true
          filters: *integration-dev_filters

      - test:
          name: test-older-docker-altogether-dev
          executor: orb-tools/node
          test-all-in-one-command: true
          docker-version: v18.09.3
          docker-compose-version: 1.22.0
          dockerize-version: v0.6.0
          goss-version: v0.3.5
          filters: *integration-dev_filters

      # ci-docker
      - test:
          name: test-latest-ci-docker-dev
          executor: orb-tools/node-cci
          filters: *integration-dev_filters

      - test:
          name: test-older-ci-docker-dev
          executor: orb-tools/node-cci
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          goss-version: v0.3.4
          filters: *integration-dev_filters

      - test:
          name: test-latest-ci-docker-altogether-dev
          executor: orb-tools/node-cci
          test-all-in-one-command: true
          filters: *integration-dev_filters

      - test:
          name: test-older-ci-docker-altogether-dev
          executor: orb-tools/node-cci
          test-all-in-one-command: true
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          goss-version: v0.3.3
          filters: *integration-dev_filters

      # oracle
      - test:
          name: test-latest-oracle-dev
          executor: orb-tools/oracle
          filters: *integration-dev_filters

      - test:
          name: test-older-oracle-dev
          executor: orb-tools/oracle
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          goss-version: v0.3.2
          filters: *integration-dev_filters

      - test:
          name: test-latest-oracle-altogether-dev
          executor: orb-tools/oracle
          test-all-in-one-command: true
          filters: *integration-dev_filters

      - test:
          name: test-older-oracle-altogether-dev
          executor: orb-tools/oracle
          test-all-in-one-command: true
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          goss-version: v0.3.1
          filters: *integration-dev_filters

      # triggered by master branch commits
      # build/publish
      - docker/publish:
          name: test-publish-machine-master
          context: orb-publishing
          dockerfile: test.Dockerfile
          image: circlecipublic/docker-orb-test
          tag: $CIRCLE_BUILD_NUM-$CIRCLE_SHA1
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASS
          filters: *integration-master_filters

      - docker/publish:
          name: test-publish-docker-master
          executor: docker/docker
          context: orb-publishing
          use-remote-docker: true
          dockerfile: test.Dockerfile
          image: circlecipublic/docker-orb-test
          tag: $CIRCLE_BUILD_NUM-$CIRCLE_SHA1
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASS
          filters: *integration-master_filters

      # alpine
      - test:
          name: test-latest-alpine-master
          executor: orb-tools/alpine
          filters: *integration-master_filters
          pre-steps: [run: apk add gnupg]

      - test:
          name: test-older-alpine-master
          executor: orb-tools/alpine
          docker-version: v18.09.4
          docker-compose-version: 1.17.1
          dockerize-version: v0.4.0
          filters: *integration-master_filters
          pre-steps: [run: apk add gnupg]

      - test:
          name: test-latest-alpine-altogether-master
          executor: orb-tools/alpine
          test-all-in-one-command: true
          filters: *integration-master_filters
          pre-steps: [run: apk add gnupg]

      - test:
          name: test-older-alpine-altogether-master
          executor: orb-tools/alpine
          test-all-in-one-command: true
          docker-version: v18.09.4
          docker-compose-version: 1.17.1
          dockerize-version: v0.4.0
          filters: *integration-master_filters
          pre-steps: [run: apk add gnupg]

      # machine
      - test:
          name: test-latest-machine-master
          executor: orb-tools/machine
          filters: *integration-master_filters

      - test:
          name: test-older-machine-master
          executor: orb-tools/machine
          docker-version: v17.09.0-ce
          docker-compose-version: 1.20.0
          dockerize-version: v0.2.0
          filters: *integration-master_filters

      - test:
          name: test-latest-machine-altogether-master
          executor: orb-tools/machine
          test-all-in-one-command: true
          filters: *integration-master_filters

      - test:
          name: test-older-machine-altogether-master
          executor: orb-tools/machine
          test-all-in-one-command: true
          docker-version: v17.09.0-ce
          docker-compose-version: 1.20.0
          dockerize-version: v0.2.0
          filters: *integration-master_filters

      # mac
      - test:
          name: test-latest-mac-master
          executor: orb-tools/macos
          filters: *integration-master_filters

      - test:
          name: test-older-mac-master
          executor: orb-tools/macos
          docker-version: v17.12.1-ce
          docker-compose-version: 1.21.2
          dockerize-version: v0.5.0
          filters: *integration-master_filters

      - test:
          name: test-latest-mac-altogether-master
          executor: orb-tools/macos
          test-all-in-one-command: true
          filters: *integration-master_filters

      - test:
          name: test-older-mac-altogether-master
          executor: orb-tools/macos
          test-all-in-one-command: true
          docker-version: v17.12.1-ce
          docker-compose-version: 1.21.2
          dockerize-version: v0.5.0
          filters: *integration-master_filters

      # docker
      - test:
          name: test-latest-docker-master
          executor: orb-tools/node
          filters: *integration-master_filters

      - test:
          name: test-older-docker-master
          executor: orb-tools/node
          docker-version: v18.09.3
          docker-compose-version: 1.22.0
          dockerize-version: v0.6.0
          filters: *integration-master_filters

      - test:
          name: test-latest-docker-altogether-master
          executor: orb-tools/node
          test-all-in-one-command: true
          filters: *integration-master_filters

      - test:
          name: test-older-docker-altogether-master
          executor: orb-tools/node
          test-all-in-one-command: true
          docker-version: v18.09.3
          docker-compose-version: 1.22.0
          dockerize-version: v0.6.0
          filters: *integration-master_filters

      # ci-docker
      - test:
          name: test-latest-ci-docker-master
          executor: orb-tools/node-cci
          filters: *integration-master_filters

      - test:
          name: test-older-ci-docker-master
          executor: orb-tools/node-cci
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          filters: *integration-master_filters

      - test:
          name: test-latest-ci-docker-altogether-master
          executor: orb-tools/node-cci
          test-all-in-one-command: true
          filters: *integration-master_filters

      - test:
          name: test-older-ci-docker-altogether-master
          executor: orb-tools/node-cci
          test-all-in-one-command: true
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          filters: *integration-master_filters

      # oracle
      - test:
          name: test-latest-oracle-master
          executor: orb-tools/oracle
          filters: *integration-master_filters

      - test:
          name: test-older-oracle-master
          executor: orb-tools/oracle
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          filters: *integration-master_filters

      - test:
          name: test-latest-oracle-altogether-master
          executor: orb-tools/oracle
          test-all-in-one-command: true
          filters: *integration-master_filters

      - test:
          name: test-older-oracle-altogether-master
          executor: orb-tools/oracle
          test-all-in-one-command: true
          docker-version: v18.06.2-ce
          docker-compose-version: 1.23.1
          dockerize-version: v0.3.0
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          ssh-fingerprints: d9:97:a8:58:12:13:40:59:48:96:f8:10:be:b8:ba:07
          context: orb-publishing
          orb-name: circleci/docker
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          ssh-fingerprints: d9:97:a8:58:12:13:40:59:48:96:f8:10:be:b8:ba:07
          context: orb-publishing
          orb-name: circleci/docker
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          ssh-fingerprints: d9:97:a8:58:12:13:40:59:48:96:f8:10:be:b8:ba:07
          context: orb-publishing
          orb-name: circleci/docker
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
